---

# General timeout,
# typically used within the k8s module for wait durations.
# One of the most time-consuming containers to start is Keycloak,
# which may take 7 minutes or so to become ready.
wait_timeout: 600
# Wait for volume binding?
# Probably unless multi-zone deployments
# where the PVC will not bind until the 'consumer' pod appears.
wait_for_bind: no
# Volume binding timeout (seconds)
bind_timeout: 60

# The infrastructure database version.
# For AWX the minimum version is 9.6+
pg_version: '12.2'

# Postgres superuser details
pg_user: governor
pg_user_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
pg_database: governor

# CPU and Memory requests and limits
pg_cpu_request: 250m
pg_cpu_limit: 1000m
pg_mem_request: 100Mi
pg_mem_limit: 500Mi
