---

# General timeout,
# typically used within the k8s module for wait durations.
# One of the most time-consuming containers to start is Keycloak,
# which may take 7 minutes or so to become ready.
wait_timeout: 600
# Wait for volume binding?
# Probably unless multi-zone deployments
# where the PVC will not bind until the 'consumer' pod appears.
wait_for_bind: no
# Volume binding timeout (seconds)
bind_timeout: 60

# The database version.
pg_image_registry: docker.io
pg_image_name: postgres
pg_image_version: '12.2'
# A pull-secret name.
# If you need a pull secret to pull the image you must create it
# in the chosen namespace and provide the name of it in this variable.
all_image_preset_pullsecret_name: ''

# CPU and Memory requests and limits
pg_cpu_request: 250m
pg_cpu_limit: 500m
pg_mem_request: 100Mi
pg_mem_limit: 500Mi
