---

# Deploy (or un-deploy)?
# One of 'present' or 'absent'.
pg_state: present

# Namespace
pg_namespace: postgres

# The database volume size (Gi).
pg_vol_size_g: 50
# The StorageClass of the postgres persistent volume.
# An blank class implied the cluster default.
pg_vol_storageclass: " "

# Root-user variables
pg_user: postgres
pg_user_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters,digits') }}"
pg_database: postgres
