---

# Deploy (or un-deploy)?
# One of 'present' or 'absent'.
pg_state: present

# Namespace
pg_namespace: postgres

# The database volume size (Gi).
#
# If this is set to '0' then the deployment
# interprets this as an 'EmptyDir' volume in Kubernetes.
# Using an EmptyDir is useful for short-lived databases
# or for recovery tests.
pg_vol_size_g: 50
# The StorageClass of the postgres persistent volume.
# A blank class implied the cluster default.
# Unused if 'pg_vol_size_g' is '0'
pg_vol_storageclass: " "

# The volume size (Gi) of a separate 'pgcopy' volume.
# The volume is mounted into the database container
# at '/pgcopy'. If the volume size defined here is '0'
# no pg-copy volume is created.
#
# You might create a pg-copy volume to provide an shared EFS/NFS volume
# for copy operations (typically used in our fragmentor).
pg_copy_vol_size_g: 0
# The StorageClass of the persistent volume.
# A blank class implied the cluster default.
pg_copy_vol_storageclass: " "

# Root-user variables
pg_user: postgres
pg_user_password: "{{ lookup('password', '/dev/null length=8 chars=ascii_letters,digits') }}"
pg_database: postgres

# An auxiliary user.
#
# If you set a user, set a password and database.
# If set an 'init' configmap is written to the DB container
# that is used to create the user and database.
# If pg_aux_user_is_superuser then the user is given SUPERUSER
# rights in the DB.
pg_aux_user: ''
pg_aux_user_password: ''
pg_aux_database: ''
pg_aux_user_is_superuser: yes

# The postgres configuration file.
#
# What is placed here is written to the container as '/tmp/postgresql.conf',
# which is then copied to 'PGDATA/postgresql.conf' at run-time
# by our initialisation script '01-init.sh'.
#
# The pg_configuration can be used to set any postgres configuration
# parameter: -
#
#   pg_configuration: |
#     listen_addresses = '*'
#     autovacuum_max_workers = 2
#     logging_collector = true
#     log_min_messages = notice
#     max_worker_processes = 2
#     max_parallel_workers = 2
#     max_parallel_workers_per_gather = 2
#     max_wal_size = 1GB
#     shared_buffers = 128kB
#     synchronous_commit = off
#     work_mem = 4MB
pg_configuration: |
  listen_addresses = '*'

# A pull-secret for public images pulled from DockerHub.
# If set this is the base-64 string that can be used as the value
# in our Kubernetes Secret as the .dockerconfigjson value.
# If set it is applied to the ServiceAccount in the namespace
# and applied to Pods that use that namespace.
pg_dockerhub_pullsecret: ''
